import os

root_directory: str = os.environ.get('LOCAL_ABSOLUTE_PATH_FILES')

list_dirs: tuple = (
    'export/export_nw/flat_export_nw_tracking',
    'export/export_nw/flat_export_nw_tracking_update',
    'export/export_vsk/flat_export_vsk_tracking',
    'export/export_vsk/flat_export_vsk_tracking_update',
    'export/lines_nle/flat_export_nle',
    'export/lines_nutep/flat_export_nutep_tracking',
    'export/lines_nutep/flat_export_nutep_tracking_update',


    'import/import_nw/flat_import_nw',
    'import/import_vsk/flat_import_vsk_tracking',
    'import/import_vsk/flat_import_vsk_tracking_update',
    'import/lines_nle/admiral',
    'import/lines_nle/akkon_lines',
    'import/lines_nle/arkas',
    'import/lines_nle/cma_cgm',
    'import/lines_nle/cosco',
    'import/lines_nle/economou',
    'import/lines_nle/evergreen',
    'import/lines_nle/fesco',
    'import/lines_nle/flat_import_nle',
    'import/lines_nle/lam',
    'import/lines_nle/lancer',
    'import/lines_nle/lider_line',
    'import/lines_nle/maersk',
    'import/lines_nle/major',
    'import/lines_nle/medkon',
    'import/lines_nle/milaha',
    'import/lines_nle/msc',
    'import/lines_nle/one',
    'import/lines_nle/oocl',
    'import/lines_nle/pjsc_transcontainer',
    'import/lines_nle/rc_line',
    'import/lines_nle/reel_shipping',
    'import/lines_nle/silmar',
    'import/lines_nle/ucak_line',
    'import/lines_nle/verim',
    'import/lines_nle/yang_ming',
    'import/lines_nle/zim',
    'import/lines_nle/ovp',
    'import/lines_nle/boat_link',
    'import/lines_nle/maas',
    'import/lines_nle/sinokor',
    'import/lines_nle/xinhelu',
    'import/lines_nle/verim_uneti',
    'import/lines_nle/c_star',

    'import/lines_nutep/admiral',
    'import/lines_nutep/akkon_lines',
    'import/lines_nutep/arkas',
    'import/lines_nutep/cma_cgm',
    'import/lines_nutep/cosco',
    'import/lines_nutep/economou',
    'import/lines_nutep/evergreen',
    'import/lines_nutep/fesco',
    'import/lines_nutep/flat_import_nutep_tracking',
    'import/lines_nutep/flat_import_nutep_tracking_update',
    'import/lines_nutep/lam',
    'import/lines_nutep/lancer',
    'import/lines_nutep/lider_line',
    'import/lines_nutep/maersk',
    'import/lines_nutep/major',
    'import/lines_nutep/medkon',
    'import/lines_nutep/milaha',
    'import/lines_nutep/msc',
    'import/lines_nutep/one',
    'import/lines_nutep/oocl',
    'import/lines_nutep/pjsc_transcontainer',
    'import/lines_nutep/rc_line',
    'import/lines_nutep/reel_shipping',
    'import/lines_nutep/silmar',
    'import/lines_nutep/ucak_line',
    'import/lines_nutep/verim',
    'import/lines_nutep/yang_ming',
    'import/lines_nutep/zim',
    'import/lines_nutep/ovp',
    'import/lines_nutep/boat_link',
    'import/lines_nutep/maas',
    'import/lines_nutep/sinokor',
    'import/lines_nutep/xinhelu',
    'import/lines_nutep/verim_uneti',
    'import/lines_nutep/c_star',


    'fts/flat_fts',
    'fts/kz_mir',

    'rzhd/rzhd_ktk',
    'rzhd/rzhd_novorossiysk',
    'rzhd/rzhd_petersburg',
    'rzhd/rzhd_weekly',

    'reference/reference_compass',
    'reference/reference_container_type',
    'reference/reference_import_tracking',
    'reference/reference_inn',
    'reference/reference_inn_by_api',
    'reference/reference_is_empty',
    'reference/reference_lines',
    'reference/reference_morservice',
    'reference/reference_region',
    'reference/reference_report_on_order',
    'reference/reference_ship',
    'reference/reference_statistics',
    'reference/reference_tnved2',
    'reference/reference_spardeck',
    'reference/reference_morservice_all',
    'reference/reference_ref',

    'RabbitMQ/errors',
    'RabbitMQ/json',
    'RabbitMQ/msg',
    'RabbitMQ/update',

    'Morservice/done',
    'Morservice/json',

    'auto_tracking',

    'production_industry'

)
